name: Update GitHub Streak Stats

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download streak stats image
        run: |
          curl -o assets/streak-stats.svg "https://streak-stats.demolab.com?user=muzz05&theme=noctis_minimus&hide_border=true"

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/streak-stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update streak stats SVG"
          git push
